version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: localex-opensearch
    environment:
      - cluster.name=localex-search
      - node.name=localex-node-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_PERFORMANCE_ANALYZER_AGENT_CLIENT=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - opensearch-logs:/usr/share/opensearch/logs
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - localex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: localex-opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - "OPENSEARCH_HOSTS=https://opensearch:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - localex-network
    depends_on:
      opensearch:
        condition: service_healthy

volumes:
  opensearch-data:
    driver: local
  opensearch-logs:
    driver: local

networks:
  localex-network:
    driver: bridge
